baseURL = ""
languageCode = "en-us"
title = "slate theme demo"
theme = "slate"
publishDir = "public"
themesDir = "themes"

[params]
Favicon = "favicon.ico"
OpenLinksInNewWindow = true

  [[params.nav]]
  name = "favorites"
  tag = "favorite"
  icon = "star"

  [[params.nav]]
  name = "search"
  tag = "search"
  icon = "search"

  [[params.nav]]
  name = "engineers"
  tag = "engineers"
  icon = "shopping-basket"

  [[params.nav]]
  name = "structural"
  tag = "structural"
  icon = "headphones"

  [[params.nav]]
  name = "video"
  tag = "video"
  icon = "video-camera"
